In [2]:
import duckdb

duckdb.sql("""
    SELECT doi, title, publisher, published_date
    FROM '../data/bronze/bronze_crossref_works_20260616T175443Z_9774ad9f-e6fc-4fca-ad10-0ca914ad9c38.parquet'
    LIMIT 10
""").show()

IOException: IO Error: No files found that match the pattern "../data/bronze/bronze_crossref_works_20260616T175443Z_9774ad9f-e6fc-4fca-ad10-0ca914ad9c38.parquet"

In [15]:
duckdb.sql("""
    DESCRIBE SELECT doi, title, publisher, published_date
    FROM '../data/bronze/bronze_crossref_works_20260616T175443Z_9774ad9f-e6fc-4fca-ad10-0ca914ad9c38.parquet'
    LIMIT 10
""").show()

┌────────────────┬─────────────┬─────────┬─────────┬─────────┬─────────┐
│  column_name   │ column_type │  null   │   key   │ default │  extra  │
│    varchar     │   varchar   │ varchar │ varchar │ varchar │ varchar │
├────────────────┼─────────────┼─────────┼─────────┼─────────┼─────────┤
│ doi            │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ title          │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ publisher      │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ published_date │ DATE        │ YES     │ NULL    │ NULL    │ NULL    │
└────────────────┴─────────────┴─────────┴─────────┴─────────┴─────────┘

In [17]:
import numpy as np
import pandas as pd

duckdb.sql("""
    SELECT *
    FROM '../data/bronze/bronze_crossref_works_20260616T175443Z_9774ad9f-e6fc-4fca-ad10-0ca914ad9c38.parquet'
    LIMIT 20
""").df()

,doi,title,publication_type,publisher,source,prefix,member,score,container_title,short_container_title,...,url,resource_url,issn_json,issn_type_json,authors_json,license_json,links_json,content_domain_json,journal_issue_json,extra_metadata_json
0,10.1157/13053457,Prevalencia del uso preconcepcional del ácido ...,journal-article,Elsevier BV,Crossref,10.1016,78,1.0,Atención Primaria,Aten Primaria,...,https://doi.org/10.1157/13053457,http://db.doyma.es/cgi-bin/wdbcgi.exe/doyma/mr...,"[""0212-6567"",""1578-1275""]","[{""value"":""0212-6567"",""type"":""print""},{""value""...","[{""given"":""A"",""family"":""Pérez-Vázquez"",""sequen...","[{""start"":{""date-parts"":[[2203,10,1]],""date-ti...","[{""URL"":""https://api.elsevier.com/content/arti...","{""domain"":[],""crossmark-restriction"":false}","{""issue"":""7"",""published-print"":null,""published...","{""alternative-id"":[""13002413""]}"
1,10.1157/13053459,Mastopatía tras tratamiento con estradiol y pa...,journal-article,Elsevier BV,Crossref,10.1016,78,1.0,Atención Primaria,Aten Primaria,...,https://doi.org/10.1157/13053459,http://db.doyma.es/cgi-bin/wdbcgi.exe/doyma/mr...,"[""0212-6567"",""1578-1275""]","[{""value"":""0212-6567"",""type"":""print""},{""value""...","[{""given"":""A"",""family"":""Piedra Cerezal"",""seque...","[{""start"":{""date-parts"":[[2203,10,1]],""date-ti...","[{""URL"":""https://api.elsevier.com/content/arti...","{""domain"":[],""crossmark-restriction"":false}","{""issue"":""7"",""published-print"":null,""published...","{""alternative-id"":[""13002413""]}"
2,10.1157/13053456,Sonambulismo asociado con zolpidem,journal-article,Elsevier BV,Crossref,10.1016,78,1.0,Atención Primaria,Aten Primaria,...,https://doi.org/10.1157/13053456,http://db.doyma.es/cgi-bin/wdbcgi.exe/doyma/mr...,"[""0212-6567"",""1578-1275""]","[{""value"":""0212-6567"",""type"":""print""},{""value""...","[{""given"":""M"",""family"":""Yanes Baonza"",""sequenc...","[{""start"":{""date-parts"":[[2203,10,1]],""date-ti...","[{""URL"":""https://api.elsevier.com/content/arti...","{""domain"":[],""crossmark-restriction"":false}","{""issue"":""7"",""published-print"":null,""published...","{""alternative-id"":[""13002413""]}"
3,10.1157/13053452,Respuesta de la autora,journal-article,Elsevier BV,Crossref,10.1016,78,1.0,Atención Primaria,Aten Primaria,...,https://doi.org/10.1157/13053452,http://db.doyma.es/cgi-bin/wdbcgi.exe/doyma/mr...,"[""0212-6567"",""1578-1275""]","[{""value"":""0212-6567"",""type"":""print""},{""value""...","[{""given"":""I"",""family"":""Fernández Fernández"",""...","[{""start"":{""date-parts"":[[2203,10,1]],""date-ti...","[{""URL"":""https://api.elsevier.com/content/arti...","{""domain"":[],""crossmark-restriction"":false}","{""issue"":""7"",""published-print"":null,""published...","{""alternative-id"":[""13002413""]}"
4,10.1157/13053449,Hepatitis C: diagnóstico y prevención desde la...,journal-article,Elsevier BV,Crossref,10.1016,78,1.0,Atención Primaria,Aten Primaria,...,https://doi.org/10.1157/13053449,http://db.doyma.es/cgi-bin/wdbcgi.exe/doyma/mr...,"[""0212-6567"",""1578-1275""]","[{""value"":""0212-6567"",""type"":""print""},{""value""...","[{""given"":""JI"",""family"":""Alastrué Loscos"",""seq...","[{""start"":{""date-parts"":[[2203,10,1]],""date-ti...","[{""URL"":""https://api.elsevier.com/content/arti...","{""domain"":[],""crossmark-restriction"":false}","{""issue"":""7"",""published-print"":null,""published...","{""alternative-id"":[""13002413""]}"
5,10.1157/13053460,Intoxicación por paracetamol líquidoen menores...,journal-article,Elsevier BV,Crossref,10.1016,78,1.0,Atención Primaria,Aten Primaria,...,https://doi.org/10.1157/13053460,http://db.doyma.es/cgi-bin/wdbcgi.exe/doyma/mr...,"[""0212-6567"",""1578-1275""]","[{""value"":""0212-6567"",""type"":""print""},{""value""...","[{""given"":""E"",""family"":""Garcés Redolat"",""seque...","[{""start"":{""date-parts"":[[2203,10,1]],""date-ti...","[{""URL"":""https://api.elsevier.com/content/arti...","{""domain"":[],""crossmark-restriction"":false}","{""issue"":""7"",""published-print"":null,""published...","{""alternative-id"":[""13002413""]}"
6,10.1157/13053448,Respuesta de los autores,journal-article,Elsevier BV,Crossref,10.1016,78,1.0,Atención Primaria,Aten Primaria,...,https://doi.org/10.1157/13053448,http://db.doyma.es/cgi-bin/wdbcgi.exe/doyma/mr...,"[""0212-6567"",""1578-1275""]","[{""value"":""0212-6567"",""type"":""print""},{""value""...","[{""given"":""M.A"",""family"":""Martínez Adell"",""seq...","[{""start"":{""date-parts"":[[2203,10,1]],""date-ti...","[{""URL"":""https://api.elsevier.com/content/arti...","{""domain"":[],""crossmark-restriction"":false}","{""issue"":""7"",""published-print"":null,""published...","{""alternative-id"":[""13002413""]}"
7,10.1157/13053451,Prevalencia de hepatitis A y hepatopatías crón...,journal-article,Elsevier BV,Crossref,10.1016,78,1.0,Atención Primaria,Aten Primaria,...,https://doi.org/10.1157/13053451,http://db.doyma.es/cgi-bin/wdbcgi.exe/doyma/mr...,"[""0212-6567"",""1578-1275""]","[{""value"":""0212-6567"",""type"":""print""},{""value""...","[{""given"":""P"",""family"":""Bachiller Luque"",""sequ...","[{""start"":{""date-parts"":[[2203,10,1]],""date-ti...","[{""URL"":""https://api.elsevier.com/content/arti...","{""domain"":[],""crossmark-restriction"":false}","{""issue"":""7"",""published-print"":null,""published...","{""alternative-id"":[""13002413""]}"
8,10.1157/13053458,La espirometría en el diagnóstico de la enferm...,journal-article,Elsevier BV,Crossref,10.1016,78,1.0,Atención Primaria,Aten Primaria,...,https://doi.org/10.1157/13053458,http://db.doyma.es/cgi-bin/wdbcgi.exe/doyma/mr...,"[""0212-6567"",""1578-1275""]","[{""value"":""0212-6567"",""type"":""print""},{""value""...","[{""given"":""JM"",""family"":""Manresa Presasa"",""seq...","[{""start"":{""date-parts"":[[2203,10,1]],""date-ti...","[{""URL"":""https://api.elsevier.com/content/arti...","{""domain"":[],""crossmark-restriction"":false}","{""issue"":""7"",""published-print"":null,""published...","{""alternative-id"":[""13002413""]}"
9,10.1157/13053723,Análisis de la demanda en los servicios de urg...,journal-article,Elsevier BV,Crossref,10.1016,78,1.0,Atención Primaria,Aten Primaria,...,https://doi.org/10.1157/13053723,http://db.doyma.es/cgi-bin/wdbcgi.exe/doyma/mr...,"[""0212-6567"",""1578-1275""]","[{""value"":""0212-6567"",""type"":""print""},{""value""...","[{""given"":""E"",""family"":""Torné Vilagrasa"",""sequ...","[{""start"":{""date-parts"":[[2203,10,1]],""date-ti...","[{""URL"":""https://api.elsevier.com/content/arti...","{""domain"":[],""crossmark-restriction"":false}","{""issue"":""7"",""published-print"":null,""published...","{""alternative-id"":[""13002413""]}"
10,10.1157/13053468,"Una apuesta por la calidad, la seriedad y la i...",journal-article,Elsevier BV,Crossref,10.1016,78,1.0,Atención Primaria,Aten Primaria,...,https://doi.org/10.1157/13053468,http://db.doyma.es/cgi-bin/wdbcgi.exe/doyma/mr...,"[""0212-6567"",""1578-1275""]","[{""value"":""0212-6567"",""type"":""print""},{""value""...","[{""given"":""M"",""family"":""Ferran Mercadé"",""seque...","[{""start"":{""date-parts"":[[2203,10,1]],""date-ti...","[{""URL"":""https://api.elsevier.com/content/arti...","{""domain"":[],""crossmark-restriction"":false}","{""issue"":""7"",""published-print"":null,""published...","{""alternative-id"":[""13002413""]}"
11,10.1157/13053466,Comentario: Prevención de los factores de ries...,journal-article,Elsevier BV,Crossref,10.1016,78,1.0,Atención Primaria,Aten Primaria,...,https://doi.org/10.1157/13053466,http://db.doyma.es/cgi-bin/wdbcgi.exe/doyma/mr...,"[""0212-6567"",""1578-1275""]","[{""value"":""0212-6567"",""type"":""print""},{""value""...","[{""given"":""P.J"",""family"":""Ruiz Lázaro"",""sequen...","[{""start"":{""date-parts"":[[2203,10,1]],""date-ti...","[{""URL"":""https://api.elsevier.com/content/arti...","{""domain"":[],""crossmark-restriction"":false}","{""issue"":""7"",""published-print"":null,""published...","{""alternative-id"":[""13002413""]}"
12,10.1157/13053453,Profundizando en los porqués y los cómos de la...,journal-article,Elsevier BV,Crossref,10.1016,78,1.0,Atención Primaria,Aten Primaria,...,https://doi.org/10.1157/13053453,http://db.doyma.es/cgi-bin/wdbcgi.exe/doyma/mr...,"[""0212-6567"",""1578-1275""]","[{""value"":""0212-6567"",""type"":""print""},{""value""...","[{""given"":""MA"",""family"":""Prieto Rodríguez"",""se...","[{""start"":{""date-parts"":[[2203,10,1]],""date-ti...","[{""URL"":""https://api.elsevier.com/content/arti...","{""domain"":[],""crossmark-restriction"":false}","{""issue"":""7"",""published-print"":null,""published...","{""alternative-id"":[""13002413""]}"
13,10.1157/13053455,Síndrome de latigazo cervical y pruebas radiol...,journal-article,Elsevier BV,Crossref,10.1016,78,1.0,Atención Primaria,Aten Primaria,...,https://doi.org/10.1157/13053455,http://db.doyma.es/cgi-bin/wdbcgi.exe/doyma/mr...,"[""0212-6567"",""1578-1275""]","[{""value"":""0212-6567"",""type"":""print""},{""value""...","[{""given"":""G"",""family"":""Burillo-Putze"",""sequen...","[{""start"":{""date-parts"":[[2203,10,1]],""date-ti...","[{""URL"":""https://api.elsevier.com/content/arti...","{""domain"":[],""crossmark-restriction"":false}","{""issue"":""7"",""published-print"":null,""published...","{""alternative-id"":[""13002413""]}"
14,10.1157/13053467,Factores de riesgo relacionados con trastornos...,journal-article,Elsevier BV,Crossref,10.1016,78,1.0,Atención Primaria,Aten Primaria,...,https://doi.org/10.1157/13053467,http://db.doyma.es/cgi-bin/wdbcgi.exe/doyma/mr...,"[""0212-6567"",""1578-1275""]","[{""value"":""0212-6567"",""type"":""print""},{""value""...","[{""given"":""M"",""family"":""Díaz Benavente"",""seque...","[{""start"":{""date-parts"":[[2203,10,1]],""date-ti...","[{""URL"":""https://api.elsevier.com/content/arti...","{""domain"":[],""crossmark-restriction"":false}","{""issue"":""7"",""published-print"":null,""published...","{""alternative-id"":[""13002413""]}"
15,10.1157/13053454,Respuesta de los autores,journal-article,Elsevier BV,Crossref,10.1016,78,1.0,Atención Primaria,Aten Primaria,...,https://doi.org/10.1157/13053454,http://db.doyma.es/cgi-bin/wdbcgi.exe/doyma/mr...,"[""0212-6567"",""1578-1275""]","[{""value"":""0212-6567"",""type"":""print""},{""value""...","[{""given"":""S"",""family"":""Castiella"",""sequence"":...","[{""start"":{""date-parts"":[[2203,10,1]],""date-ti...","[{""URL"":""https://api.elsevier.com/content/arti...","{""domain"":[],""crossmark-restriction"":false}","{""issue"":""7"",""published-print"":null,""published...","{""alternative-id"":[""13002413""]}"
16,10.1157/13053463,El riesgo coronario en España y el tratamiento...,journal-article,Elsevier BV,Crossref,10.1016,78,1.0,Atención Primaria,Aten Primaria,...,https://doi.org/10.1157/13053463,http://db.doyma.es/cgi-bin/wdbcgi.exe/doyma/mr...,"[""0212-6567"",""1578-1275""]","[{""value"":""0212-6567"",""type"":""print""},{""value""...","[{""given"":""A"",""family"":""Maiques Galán"",""sequen...","[{""start"":{""date-parts"":[[2203,10,1]],""date-ti...","[{""URL"":""https://api.elsevier.com/content/arti...","{""domain"":[],""crossmark-restriction"":false}","{""issue"":""7"",""published-print"":null,""published...","{""alternative-id"":[""13002413""]}"
17,10.1157/13053461,Violencia en la pareja: papel del médico de fa...,journal-article,Elsevier BV,Crossref,10.1016,78,1.0,Atención Primaria,Aten Primaria,...,https://doi.org/10.1157/13053461,http://db.doyma.es/cgi-bin/wdbcgi.exe/doyma/mr...,"[""0212-6567"",""1578-1275""]","[{""value"":""0212-6567"",""type"":""print""},{""value""...","[{""given"":""MC"",""family"":""Fernández Alonso"",""se...","[{""start"":{""date-parts"":[[2203,10,1]],""date-ti...","[{""URL"":""https://api.elsevier.com/content/arti...","{""domain"":[],""crossmark-restriction"":false}","{""issue"":""7"",""published-print"":null,""published...","{""alternative-id"":[""13002413""]}"
18,10.1157/13053464,Estudio de la marca en la prescripción de gené...,journal-article,Elsevier BV,Crossref,10.1016,78,1.0,Atención Primaria,Aten Primaria,...,https://doi.org/10.1157/13053464,http://db.doyma.es/cgi-bin/wdbcgi.exe/doyma/mr...,"[""0212-6567"",""1578-1275""]","[{""value"":""0212-6567"",""type"":""print""},{""value""...","[{""given"":""G"",""family"":""Carmona Ibáñez"",""seque...","[{""start"":{""date-parts"":[[2203,10,1]],""date-ti...","[{""URL"":""https://api.elsevier.com/content/arti...","{""domain"":[],""crossmark-restriction"":false}","{""issue"":""7"",""published-print"":null,""published...","{""alternative-id"":[""13002413""]}"
19,10.1157/13053465,Epidemiología e impacto de la incontinencia ur...,journal-article,Elsevier BV,Crossref,10.1016,78,1.0,Atención Primaria,Aten Primaria,...,https://doi.org/10.1157/13053465,http://db.doyma.es/cgi-bin/wdbcgi.exe/doyma/mr...,"[""0212-6567"",""1578-1275""]","[{""value"":""0212-6567"",""type"":""print""},{""value""...","[{""given"":""E"",""family"":""Nieto Blanco"",""sequenc...","[{""start"":{""date-parts"":[[2203,10,1]],""date-ti...","[{""URL"":""https://api.elsevier.com/content/arti...","{""domain"":[],""crossmark-restriction"":false}","{""issue"":""7"",""published-print"":null,""published...","{""alternative-id"":[""13002413""]}"

In [54]:
#duck db!

import numpy as np
import pandas as pd
pd.set_option("display.max_rows", 200)

duckdb.sql("""
    SELECT doi, COUNT(DISTINCT record_hash)
    FROM '../data/bronze/bronze_crossref_works_20260616T215720Z_b4254f30-4316-4d24-b1d7-15850a048a68.parquet'
    GROUP BY doi
    HAVING COUNT(DISTINCT record_hash) > 1
""").df()

Empty DataFrame
Columns: [doi, count(DISTINCT record_hash)]
Index: []

In [56]:
duckdb.sql("""
    SELECT doi, COUNT(*) AS row_count
    FROM '../data/bronze/bronze_crossref_works_20260616T221037Z_4fabc488-1920-48db-84d7-fe736eceefa8.parquet'
    WHERE doi IS NOT NULL
    GROUP BY doi
    HAVING COUNT(*) > 1
""").df()

Empty DataFrame
Columns: [doi, row_count]
Index: []

In [7]:
#w/o duckdb!!!

import numpy as np
import pandas as pd
pd.set_option("display.max_rows", 10)

dd = duckdb.sql("""
    SELECT *
    FROM '../data/bronze/bronze_crossref_works_*.parquet'
""").df()

In [47]:
list(set(duckdb_list) - set(no_duckdb_list))

[]

In [48]:
list(set(no_duckdb_list) - set(duckdb_list))

['bronze_created_at_utc', 'raw_file', 'staged_at_utc', 'record_hash']

In [10]:
dd['alternative_ids_json'].to_list()

['["13002413"]',
 '["13002413"]',
 '["13002413"]',
 '["13002413"]',
 '["13002413"]',
 '["13002413"]',
 '["13002413"]',
 '["13002413"]',
 '["13002413"]',
 '["13002413"]',
 '["13002413"]',
 '["13002413"]',
 '["13002413"]',
 '["13002413"]',
 '["13002413"]',
 '["13002413"]',
 '["13002413"]',
 '["13002413"]',
 '["13002413"]',
 '["13002413"]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '["21902"]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '["10.25068/dedekorkut133"]',
 '["10.25068/dedekorkut147"]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]',
 '[]']